# permissions for end users to view cedarpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cedarpolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cedarsync
    app.kubernetes.io/part-of: cedarsync
    app.kubernetes.io/managed-by: kustomize
  name: cedarpolicy-viewer-role
rules:
- apiGroups:
  - cedarsync.omegahome.net
  resources:
  - cedarpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cedarsync.omegahome.net
  resources:
  - cedarpolicies/status
  verbs:
  - get
