# permissions for end users to edit cedarpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cedarpolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cedarsync
    app.kubernetes.io/part-of: cedarsync
    app.kubernetes.io/managed-by: kustomize
  name: cedarpolicy-editor-role
rules:
- apiGroups:
  - cedarsync.omegahome.net
  resources:
  - cedarpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cedarsync.omegahome.net
  resources:
  - cedarpolicies/status
  verbs:
  - get
