---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cedarsync.omegahome.net
  resources:
  - cedarapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cedarsync.omegahome.net
  resources:
  - cedarapis/finalizers
  verbs:
  - update
- apiGroups:
  - cedarsync.omegahome.net
  resources:
  - cedarapis/status
  verbs:
  - get
  - patch
  - update
