apiVersion: cedarsync.omegahome.net/v1alpha1
kind: CedarPolicy
metadata:
  labels:
    app.kubernetes.io/name: cedarsync
    app.kubernetes.io/managed-by: kustomize
  name: cedarpolicy-sample
spec:
  # TODO(user): Add fields here
